import { DAI_ADDRESS, HYDRO_ADDRESS, USX_ADDRESS } from "./addresses";

const paths:any =  {
	USX_DAI: [USX_ADDRESS, DAI_ADDRESS],
	DAI_USX: [DAI_ADDRESS, USX_ADDRESS],
	HX_DAI: [HYDRO_ADDRESS, DAI_ADDRESS],
	DAI_HX: [DAI_ADDRESS, HYDRO_ADDRESS],
	HX_USX: [HYDRO_ADDRESS, DAI_ADDRESS, USX_ADDRESS],
	USX_HX: [USX_ADDRESS, DAI_ADDRESS, HYDRO_ADDRESS]
};

export default paths;
	
