[context.production.environment]
  NODE_ENV = "production"
[context.deploy-preview.environment]
  NODE_ENV = "staging"
[context.branch-deploy.environment]
  NODE_ENV = "development"
[context.dev.environment]
  NODE_ENV = "development"